### ISSUE TITLE
SIU acceptable use policy link is broken

### ISSUE THREAD

**Issue by milanbambhaniya** [HackSI/site#111]
https://github.com/HackSI/site/blob/5377fe517823d7071091092b36e842995cf584bf/views/home.handlebars#L15 This gives 404. 
<img width="1676" alt="Screen Shot 2019-09-12 at 9 36 20 PM" src="https://user-images.githubusercontent.com/5190149/64837964-de746180-d5a5-11e9-9cf2-1a3bf25c4967.png">

**Comment by davglass** [comment]
Thanks for pointing this out..
